-- ============================================================
-- PUJIVERSE — SEED DATA (Oct 2026 portfolio). Run AFTER schema.sql.
-- Safe to re-run: channels upsert, the other lists are replaced.
-- ============================================================
BEGIN;

-- Channels (39)
INSERT INTO channels (sno, name, channel_name, handle, category, group_name, youtube_url, viral_score, score, cpm_tier, team_size, status) VALUES
  ('1.01', 'Pujiverse AI', 'Pujiverse AI', '@pujiverseai', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiverseai', 98, 98, 'Very High', 2, 'LIVE'),
  ('1.02', 'PUJIVERSE TECH', 'PUJIVERSE TECH', '@pujiversetech', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiversetech', 89, 89, 'Very High', 2, 'LIVE'),
  ('1.03', 'Pujiverse Future', 'Pujiverse Future', '@pujiversefuture', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiversefuture', 86, 86, 'High', 1, 'LIVE'),
  ('1.04', 'Pujiverse Space', 'Pujiverse Space', '@pujiversespace', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiversespace', 85, 85, 'High', 1, 'LIVE'),
  ('1.05', 'Pujiverse Gadgets', 'Pujiverse Gadgets', '@pujiversegadgets', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiversegadgets', 83, 83, 'Very High', 1, 'LIVE'),
  ('1.06', 'Pujiverse Mystery', 'Pujiverse Mystery', '@pujiversemystery', 'Entertainment', 'Mystery & Mind', 'https://www.youtube.com/@pujiversemystery', 97, 97, 'High', 2, 'LIVE'),
  ('1.07', 'Pujiverse True Crime', 'Pujiverse True Crime', '@pujiversetruecrime', 'Entertainment', 'Mystery & Mind', 'https://www.youtube.com/@pujiversetruecrime', 96, 96, 'High', 2, 'LIVE'),
  ('1.08', 'Pujiverse Psychology', 'Pujiverse Psychology', '@pujiversepsychology', 'Education', 'Mystery & Mind', 'https://www.youtube.com/@pujiversepsychology', 95, 95, 'High', 2, 'LIVE'),
  ('1.09', 'Pujiverse Conspiracy', 'Pujiverse Conspiracy', '@pujiverseconspiracy', 'Entertainment', 'Mystery & Mind', 'https://www.youtube.com/@pujiverseconspiracy', 92, 92, 'Medium', 1, 'LIVE'),
  ('1.10', 'Pujiverse Paranormal', 'Pujiverse Paranormal', '@pujiverseparanormal', 'Entertainment', 'Mystery & Mind', 'https://www.youtube.com/@pujiverseparanormal', 88, 88, 'Medium', 1, 'LIVE'),
  ('1.11', 'Pujiverse Science', 'Pujiverse Science', '@pujiversescience', 'Science & Technology', 'Tech & Science', 'https://www.youtube.com/@pujiversescience', 90, 90, 'High', 2, 'LIVE'),
  ('1.12', 'Pujiverse Finance', 'Pujiverse Finance', '@pujiversefinance', 'Education', 'Money & Career', 'https://www.youtube.com/@PujiVerseWealth', 91, 91, 'Very High', 2, 'LIVE'),
  ('1.13', 'Pujiverse Business', 'Pujiverse Business', '@pujiversebusiness', 'Education', 'Money & Career', 'https://www.youtube.com/@pujiversebusiness', 87, 87, 'Very High', 1, 'LIVE'),
  ('1.14', 'Pujiverse Crypto', 'Pujiverse Crypto', '@pujiversecrypto', 'Education', 'Money & Career', 'https://www.youtube.com/@pujiversecrypto', 85, 85, 'Very High', 1, 'LIVE'),
  ('1.15', 'Pujiverse Real Estate', 'Pujiverse Real Estate', '@pujiverserealestate', 'Education', 'Money & Career', 'https://www.youtube.com/@pujiverserealestate', 82, 82, 'Very High', 1, 'LIVE'),
  ('1.16', 'Pujiverse Luxury', 'Pujiverse Luxury', '@pujiverseluxury', 'Entertainment', 'Money & Career', 'https://www.youtube.com/@pujiverseluxury', 84, 84, 'High', 1, 'LIVE'),
  ('1.17', 'Pujiverse Gaming', 'Pujiverse Gaming', '@pujiversegaming', 'Gaming', 'Entertainment', 'https://www.youtube.com/@PujiverseGaming', 93, 93, 'Medium', 2, 'LIVE'),
  ('1.18', 'PUJIVERSE CINE', 'PUJIVERSE CINE', '@pujiversemovies', 'Film & Animation', 'Entertainment', 'https://www.youtube.com/@PUJIVERSECINE', 87, 87, 'Medium', 2, 'LIVE'),
  ('1.19', 'Pujiverse Sports', 'Pujiverse Sports', '@pujiversesports', 'Sports', 'Entertainment', 'https://www.youtube.com/@pujiversesports', 86, 86, 'Medium', 1, 'LIVE'),
  ('1.20', 'Pujiverse Celebrity', 'Pujiverse Celebrity', '@pujiversecelebrity', 'Entertainment', 'Entertainment', 'https://www.youtube.com/@pujiversecelebrity', 89, 89, 'Medium', 1, 'LIVE'),
  ('1.21', 'PujiVerse Beatz', 'PujiVerse Beatz', '@pujiversebeatz', 'Music', 'Entertainment', 'https://www.youtube.com/@PujiVerseBeatz', 81, 81, 'Low', 1, 'LIVE'),
  ('1.22', 'Pujiverse Mind', 'Pujiverse Mind', '@pujiversemind', 'Education', 'Mystery & Mind', 'https://www.youtube.com/@PujiverseWisdom', 92, 92, 'High', 2, 'LIVE'),
  ('1.23', 'Pujiverse Motivation', 'Pujiverse Motivation', '@pujiversemotivation', 'Education', 'Learning & Culture', 'https://www.youtube.com/@pujiversemotivation', 88, 88, 'Medium', 1, 'LIVE'),
  ('1.24', 'PUJIVERSE HISTORY', 'PUJIVERSE HISTORY', '@pujiversehistory', 'Education', 'Learning & Culture', 'https://www.youtube.com/@PUJIVERSEHISTORY', 86, 86, 'Medium', 1, 'LIVE'),
  ('1.25', 'Pujiverse Languages', 'Pujiverse Languages', '@pujiverselanguages', 'Education', 'Learning & Culture', 'https://www.youtube.com/@PujiverseLingo', 79, 79, 'Medium', 1, 'LIVE'),
  ('1.26', 'PUJIVERSE KIDS', 'PUJIVERSE KIDS', '@pujiversekids', 'Education', 'Learning & Culture', 'https://www.youtube.com/@Pujiversekids', 83, 83, 'Medium', 2, 'LIVE'),
  ('1.27', 'Pujiverse Fitness', 'Pujiverse Fitness', '@pujiversefitness', 'Howto & Style', 'Lifestyle', 'https://www.youtube.com/@PujiverseFit', 85, 85, 'Medium', 1, 'LIVE'),
  ('1.28', 'Pujiverse Recipes', 'Pujiverse Recipes', '@pujiverserecipes', 'Howto & Style', 'Lifestyle', 'https://www.youtube.com/@PujiverseFood', 84, 84, 'Medium', 1, 'LIVE'),
  ('1.29', 'Pujiverse LifeStyle', 'Pujiverse LifeStyle', '@pujiverselifestyle', 'People & Blogs', 'Lifestyle', 'https://www.youtube.com/@PujiverseVlogs', 80, 80, 'Medium', 1, 'LIVE'),
  ('1.30', 'Pujiverse Devotional', 'Pujiverse Devotional', '@pujiversedevotional', 'People & Blogs', 'Learning & Culture', 'https://www.youtube.com/@PujiverseDevotional', 77, 77, 'Medium', 1, 'LIVE'),
  ('1.31', 'Pujiverse Shorts', 'Pujiverse Shorts', '@pujiverseshorts', 'People & Blogs', 'Entertainment', 'https://www.youtube.com/@pujiverseshorts', 94, 94, 'High', 2, 'LIVE'),
  ('1.32', 'Pujiverse Ocean', 'Pujiverse Ocean', '@pujiverseocean', 'Pets & Animals', 'World & Transport', 'https://www.youtube.com/@pujiverseocean', 85, 85, 'High', 1, 'LIVE'),
  ('1.33', 'Pujiverse Aviation', 'Pujiverse Aviation', '@pujiverseaviation', 'Autos & Vehicles', 'World & Transport', 'https://www.youtube.com/@pujiverseaviation', 86, 86, 'High', 1, 'LIVE'),
  ('1.34', 'Pujiverse Agriculture', 'Pujiverse Agriculture', '@pujiverseagriculture', 'Pets & Animals', 'World & Transport', 'https://www.youtube.com/@pujiverseagriculture', 88, 88, 'Medium', 1, 'LIVE'),
  ('1.35', 'Pujiverse Transport', 'Pujiverse Transport', '@pujiversetransport', 'Autos & Vehicles', 'World & Transport', 'https://www.youtube.com/@pujiversetransport', 78, 78, 'Medium', 1, 'LIVE'),
  ('1.36', 'Pujiverse Life Hacks', 'Pujiverse Life Hacks', '@pujiverselifehacks', 'Howto & Style', 'Lifestyle', 'https://www.youtube.com/@pujiverselifehacks', 82, 82, 'High', 1, 'LIVE'),
  ('1.37', 'Pujiverse Music', 'Pujiverse Music', '@pujiversemusic', 'Music', 'Entertainment', 'https://www.youtube.com/@pujiversemusic', 80, 80, 'Medium', 1, 'LIVE'),
  ('1.38', 'Pujiverse Jobs', 'Pujiverse Jobs', '@pujiversejobs', 'Education', 'Money & Career', 'https://www.youtube.com/@pujiversejobs', 80, 80, 'High', 1, 'LIVE'),
  ('1.39', 'Pujiverse Talk', 'Pujiverse Talk', '@pujiversetalk', 'People & Blogs', 'Entertainment', 'https://www.youtube.com/@pujiversetalk', 79, 79, 'Medium', 1, 'LIVE')
ON CONFLICT (sno) DO UPDATE SET name = EXCLUDED.name, channel_name = EXCLUDED.channel_name, handle = EXCLUDED.handle,
  category = EXCLUDED.category, group_name = EXCLUDED.group_name, youtube_url = EXCLUDED.youtube_url,
  viral_score = EXCLUDED.viral_score, score = EXCLUDED.score, cpm_tier = EXCLUDED.cpm_tier,
  team_size = EXCLUDED.team_size, status = EXCLUDED.status;

-- Playlists (187)
DELETE FROM playlists WHERE channel_sno IN ('1.01', '1.02', '1.03', '1.04', '1.05', '1.06', '1.07', '1.08', '1.09', '1.10', '1.11', '1.12', '1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24', '1.25', '1.26', '1.27', '1.28', '1.29', '1.30', '1.31', '1.32', '1.33', '1.34', '1.35', '1.36', '1.37', '1.38', '1.39');
INSERT INTO playlists (channel_sno, playlist_name, sort_order) VALUES
  ('1.01', 'ChatGPT Mastery — Every Trick, Prompt & Hack for 2026', 0),
  ('1.01', 'Top AI Tools of 2026 — Reviews, Comparisons & Free Alternatives', 1),
  ('1.01', 'AI Agents & Automation — Replace Hours of Work with Smart Workflows', 2),
  ('1.01', 'Make Money with AI — Proven Income Streams Using AI Tools', 3),
  ('1.01', 'AI News Weekly — Every Major AI Update Explained Simply', 4),
  ('1.02', 'iPhone vs Android — Honest Comparisons, Hidden Features & Winners', 0),
  ('1.02', 'Budget vs Premium — ₹500 vs ₹50,000 Tech Challenges', 1),
  ('1.02', 'Smartphone Hidden Features — Tricks Apple and Google Don''t Advertise', 2),
  ('1.02', 'Laptop Reviews — Best Laptops for Students, Gaming, Work & Creators', 3),
  ('1.02', 'Smart Home & Accessories — Upgrade Your Setup for 2026', 4),
  ('1.03', '2030 to 2050 — What the Future Really Looks Like', 0),
  ('1.03', 'Flying Cars, Hyperloop & The Future of Transport', 1),
  ('1.03', 'Robotics Revolution — Humanoid Robots Taking Over Work', 2),
  ('1.03', 'Brain-Computer Interfaces — Neuralink & The End of Keyboards', 3),
  ('1.03', 'Colonizing Mars & The Space Economy of 2030', 4),
  ('1.04', 'Black Holes & Cosmic Mysteries — What''s Really Out There', 0),
  ('1.04', 'Life on Other Planets — Aliens, Exoplanets & The Search for ET', 1),
  ('1.04', 'NASA, SpaceX & ISRO — Every Space Mission Updated', 2),
  ('1.04', 'Planets & Solar System — Everything You Never Learned in School', 3),
  ('1.04', 'James Webb & Hubble — Photos That Broke Astronomy', 4),
  ('1.05', 'Amazon Finds Under ₹500 — Gadgets That Feel Like Magic', 0),
  ('1.05', 'Smart Home Gadgets That Change Daily Life', 1),
  ('1.05', 'Weird Gadgets That Shouldn''t Exist But Do', 2),
  ('1.05', 'Kitchen Gadgets That Save Hours in the Kitchen', 3),
  ('1.05', 'Gift Ideas for Every Occasion & Budget', 4),
  ('1.06', 'Missing Persons Cases That Still Haunt the World', 0),
  ('1.06', 'Unexplained Historical Mysteries — Events Science Can''t Solve', 1),
  ('1.06', 'Lost Civilizations & Ancient Mysteries', 2),
  ('1.06', 'Cursed Places & Cursed Objects — Real Stories, Real Deaths', 3),
  ('1.06', 'Cryptids & Real Monster Sightings Around the World', 4),
  ('1.07', 'Serial Killers Who Shocked the World', 0),
  ('1.07', 'Perfect Crimes That Almost Got Away', 1),
  ('1.07', 'Cold Cases Finally Solved — DNA, Genealogy, and Justice Decades Later', 2),
  ('1.07', 'Unsolved Murders That Still Haunt Investigators', 3),
  ('1.07', 'Famous Con Artists & Billion-Dollar Scams', 4),
  ('1.08', 'Dark Psychology — Manipulation Tactics You Should Know', 0),
  ('1.08', 'Read People Like a Book — Body Language & Behavior Analysis', 1),
  ('1.08', 'Cognitive Biases & Why Your Brain Lies to You', 2),
  ('1.08', 'Understanding Narcissists, Sociopaths & Psychopaths', 3),
  ('1.08', 'Human Behavior Experiments That Changed Science', 4),
  ('1.09', 'Conspiracy Theories That Turned Out to Be True', 0),
  ('1.09', 'JFK, Moon Landing & Historical Conspiracies', 1),
  ('1.09', 'Secret Societies — Illuminati, Freemasons, Skull and Bones', 2),
  ('1.09', 'Big Pharma, Big Food & Corporate Cover-Ups', 3),
  ('1.09', 'UFO Disclosure — Governments Finally Admitting Aliens?', 4),
  ('1.10', 'Most Haunted Places on Earth — Real Hauntings Documented', 0),
  ('1.10', 'Real Ghost Encounters — Caught on Camera & Witness Accounts', 1),
  ('1.10', 'Demonic Encounters, Possessions & Real Exorcisms', 2),
  ('1.10', 'Near-Death Experiences & Life After Death', 3),
  ('1.10', 'Paranormal Investigations — Ghost Hunters in Action', 4),
  ('1.11', 'Mind-Blowing Science Experiments You Can Do at Home', 0),
  ('1.11', 'What Happens If... — Science Answers Your Wild Questions', 1),
  ('1.11', 'Biology Secrets — How Your Body Really Works', 2),
  ('1.11', 'Chemistry That Feels Like Magic — Reactions Explained', 3),
  ('1.11', 'Dangerous Science — The Deadliest Chemicals, Animals & Phenomena', 4),
  ('1.12', 'Passive Income Ideas — Make Money While You Sleep', 0),
  ('1.12', 'Stock Market for Beginners — Start Investing in 2026', 1),
  ('1.12', 'Personal Finance — Budget, Save, and Build Wealth on Any Income', 2),
  ('1.12', 'How the Rich Think — Money Habits of Millionaires', 3),
  ('1.12', 'Side Hustles That Actually Work — Earn ₹10K to ₹1L Extra Per Month', 4),
  ('1.13', 'From Zero to Crore — Indian Entrepreneur Success Stories', 0),
  ('1.13', 'Business Ideas for 2026 — Low Investment, High Returns', 1),
  ('1.13', 'Marketing Masterclass — Grow Any Business in 2026', 2),
  ('1.13', 'How to Start a Startup — From Idea to Funded Company', 3),
  ('1.13', 'Business Lessons from Billionaires — Elon, Ambani, Adani, Bezos', 4),
  ('1.14', 'Bitcoin Explained — From Basics to Halving, ETFs & 2026 Predictions', 0),
  ('1.14', 'Ethereum & Altcoins That Could 10x in 2026', 1),
  ('1.14', 'DeFi & Yield Farming — Earn Passive Income with Crypto', 2),
  ('1.14', 'NFTs, Web3 & The Future of Digital Ownership', 3),
  ('1.14', 'Crypto Scams, Rug Pulls & How to Protect Your Money', 4),
  ('1.15', 'First-Time Home Buyer Guide — Buy Your First Home in India', 0),
  ('1.15', 'Rental Property Investing — Build Passive Income with Real Estate', 1),
  ('1.15', 'House Flipping — Buy Low, Renovate, Sell High', 2),
  ('1.15', 'Luxury Real Estate Tours — Mansions, Penthouses & Dream Homes', 3),
  ('1.15', 'Commercial Real Estate & REITs — Invest Without Buying Property', 4),
  ('1.16', 'Inside Billionaire Homes — Mukesh Ambani, Elon Musk, Bill Gates', 0),
  ('1.16', 'Supercars, Hypercars & Cars Money Alone Can''t Buy', 1),
  ('1.16', 'Private Jets & Mega Yachts — Travel Like a Billionaire', 2),
  ('1.16', 'Most Expensive Things in the World', 3),
  ('1.16', 'Luxury Brands Decoded — Rolex, Hermès, Louis Vuitton, Ferrari', 4),
  ('1.17', 'Game Secrets — Easter Eggs Nobody Found for Years', 0),
  ('1.17', 'Impossible Gaming Challenges — Beat the Game Without...', 1),
  ('1.17', 'Top Games of 2026 — New Releases, Reviews & Hidden Gems', 2),
  ('1.17', 'Mobile Gaming & BGMI — From Rookie to Pro', 3),
  ('1.17', 'Gaming History — How Video Games Became the Biggest Industry', 4),
  ('1.18', 'Hollywood Movie Theories & Easter Eggs You Missed', 0),
  ('1.18', 'Tollywood Films — Telugu Cinema Deep Dives & Legend Tributes', 1),
  ('1.18', 'Bollywood Classics & Modern Hits — Films That Defined Generations', 2),
  ('1.18', 'Movie Endings Explained — Every Confusing Climax Decoded', 3),
  ('1.18', 'Korean, Japanese & World Cinema — Hidden Gems Beyond Hollywood', 4),
  ('1.19', 'Cricket Greatest Moments — World Cups, Records & Legends', 0),
  ('1.19', 'Football (Soccer) — Messi, Ronaldo, World Cup & Champions League', 1),
  ('1.19', 'NBA Basketball — LeBron, Jordan, Curry & Greatest Games', 2),
  ('1.19', 'F1 Racing, MMA & Combat Sports — Ultimate Athletic Drama', 3),
  ('1.19', 'Olympics & Athletics — India''s Rising Stars and Global Glory', 4),
  ('1.20', 'Bollywood Celebrity Lives — Scandals, Rises & Untold Stories', 0),
  ('1.20', 'Hollywood Rise & Fall Stories — Johnny Depp, Britney, Whitney', 1),
  ('1.20', 'Tollywood Stars — Prabhas, Mahesh Babu, Allu Arjun Journey', 2),
  ('1.20', 'K-Pop Phenomenon — BTS, BLACKPINK, Global Korean Wave', 3),
  ('1.20', 'Influencer & Creator Empire — MrBeast, CarryMinati, Ranveer Allahbadia', 4),
  ('1.21', 'Song Meanings & Lyrics Decoded — Songs You Misunderstood', 0),
  ('1.21', 'Best Music of Every Genre — Pop, Rock, Hip-Hop, Classical, Indian', 1),
  ('1.21', 'AI Music Creation with Suno — How to Make Songs from Scratch', 2),
  ('1.21', 'Music Legends — A.R. Rahman, SP Balu, Ilaiyaraaja & Global Greats', 3),
  ('1.21', 'Best Movie Songs & Background Scores — Cinematic Music Magic', 4),
  ('1.22', 'Build Unstoppable Habits — Tiny Changes, Life-Changing Results', 0),
  ('1.22', 'Stoic Philosophy — Ancient Wisdom for Modern Life', 1),
  ('1.22', 'Productivity & Deep Work — Get More Done in Less Time', 2),
  ('1.22', 'Mental Health & Emotional Mastery — Control Your Mind', 3),
  ('1.22', 'Rich Mindset vs Poor Mindset — Mental Shifts for Wealth', 4),
  ('1.23', 'Best Motivational Speeches That Changed Lives', 0),
  ('1.23', 'Rags to Riches Stories — From Nothing to Everything', 1),
  ('1.23', 'Never Give Up — Comeback Stories That Inspire Millions', 2),
  ('1.23', 'Discipline Over Motivation — Become Unstoppable', 3),
  ('1.23', 'Daily Motivation — Morning Fuel to Start Your Day Strong', 4),
  ('1.24', 'Ancient India — Maurya, Chola, Vijayanagara & Forgotten Empires', 0),
  ('1.24', 'World Wars Explained — WW1, WW2, Causes, Key Battles, Aftermath', 1),
  ('1.24', 'Brutal Rulers & Dictators — The Most Feared Leaders in History', 2),
  ('1.24', 'Lost Civilizations — Indus, Maya, Sumerian, Egyptian Mysteries', 3),
  ('1.24', 'Indian Freedom Struggle — Real Stories Beyond School Textbooks', 4),
  ('1.25', 'Learn Spanish Fast — Beginner to Conversational in 90 Days', 0),
  ('1.25', 'Learn Japanese — Anime, Manga & Travel Japanese', 1),
  ('1.25', 'Learn Korean Fast — K-Pop, K-Drama & Daily Conversation', 2),
  ('1.25', 'Indian Languages — Hindi, Telugu, Tamil, Bengali, Marathi', 3),
  ('1.25', 'English Mastery — Fluency, Grammar & Perfect Pronunciation', 4),
  ('1.26', 'ABC & 123 — Learn Letters, Numbers, Shapes & Colors', 0),
  ('1.26', 'Kids Stories — Panchatantra, Moral Stories & Fairy Tales', 1),
  ('1.26', 'Nursery Rhymes — Classic & Modern Songs for Little Ones', 2),
  ('1.26', 'Fun Science for Kids — Amazing Experiments & Facts', 3),
  ('1.26', 'Good Habits & Values for Kids — Life Lessons Through Fun', 4),
  ('1.27', '30-Day Transformation Challenges — Real Results', 0),
  ('1.27', 'Home Workouts — No Gym, No Equipment, Full Results', 1),
  ('1.27', 'Gym Training — Beginner to Advanced Lifting Guide', 2),
  ('1.27', 'Weight Loss & Fat Burn — Science-Backed Methods That Work', 3),
  ('1.27', 'Nutrition & Diet — Indian Bodybuilder & Fitness Meals', 4),
  ('1.28', 'South Indian Recipes — Dosa, Idli, Sambar, Biryani & More', 0),
  ('1.28', 'North Indian Recipes — Butter Chicken, Naan, Chole & Dal Makhani', 1),
  ('1.28', 'American & Italian Classics — Pizza, Pasta, Burgers at Home', 2),
  ('1.28', 'Chinese, Thai & Asian Recipes — Restaurant-Style at Home', 3),
  ('1.28', 'Street Food from Around the World — India, Mexico, Thailand', 4),
  ('1.29', 'Morning Routines — 5AM Club, Miracle Morning, Billionaire Routines', 0),
  ('1.29', 'Minimalism & Decluttering — Own Less, Live More', 1),
  ('1.29', 'Aesthetic Daily Life — Cozy Routines, Study Vibes, Soft Living', 2),
  ('1.29', 'Home Organization & Interior Design on a Budget', 3),
  ('1.29', 'Self-Care Rituals — Mental, Physical & Emotional Wellness', 4),
  ('1.30', 'Lord Shiva — Bhajans, Mantras & Stories of Mahadev', 0),
  ('1.30', 'Lord Krishna — Bhagavad Gita, Bhajans & Divine Leelas', 1),
  ('1.30', 'Lord Ganesha, Lord Hanuman & Beloved Hindu Deities', 2),
  ('1.30', 'Divine Mothers — Durga, Lakshmi, Saraswati & Kali', 3),
  ('1.30', 'Lord Venkateswara, Sai Baba & Lord Rama Devotional', 4),
  ('1.31', 'Mind-Blowing Facts in 60 Seconds — Daily Dose of Wow', 0),
  ('1.31', 'Best Moments from Every Pujiverse Channel', 1),
  ('1.31', 'Life Hacks That Actually Work — 60-Second Upgrades', 2),
  ('1.31', 'Viral Moments & Trending Topics — What''s Hot Right Now', 3),
  ('1.31', 'Quick Motivation & Inspiration Clips — 60 Seconds to Fire You Up', 4),
  ('1.32', 'Sharks — The Ocean''s Most Feared & Misunderstood Predators', 0),
  ('1.32', 'Whales, Dolphins & Intelligent Sea Mammals', 1),
  ('1.32', 'Deep Sea Monsters — Creatures from the Ocean''s Darkest Depths', 2),
  ('1.32', 'Coral Reefs & Colorful Tropical Fish Explored', 3),
  ('1.32', 'Aquariums, Aquascaping & Pet Fish Care Guide', 4),
  ('1.33', 'Commercial Aircraft — Boeing vs Airbus, A380, 787 Dreamliner', 0),
  ('1.33', 'Private Jets & Luxury Aviation — Inside the World of the Ultra-Rich', 1),
  ('1.33', 'Aviation History — Greatest Flights, Crashes & Turning Points', 2),
  ('1.33', 'Pilot Life, Cockpit Secrets & Airport Facts You Never Knew', 3),
  ('1.33', 'Military Aircraft & Fighter Jets — The Most Powerful Flying Machines', 4),
  ('1.34', 'Organic Gardening & Home Farming — Grow Food at Home', 0),
  ('1.34', 'Livestock & Dairy Farming — Complete Business Guide', 1),
  ('1.34', 'Agri-Business Ideas — Start a Farming Startup in 2026', 2),
  ('1.34', 'Sustainable Living & Permaculture Practices', 3),
  ('1.34', 'Technology in Farming — Drones, AI & Smart Agriculture', 4),
  ('1.35', 'World''s Greatest Trains — Bullet Trains, Luxury Rails & Indian Railways', 0),
  ('1.35', 'Electric Vehicles & Green Transport — The Future of Mobility', 1),
  ('1.35', 'Ships, Cargo & Maritime Transport — Giants of the Sea', 2),
  ('1.35', 'Mega Infrastructure — Bridges, Tunnels, Highways & Engineering Marvels', 3),
  ('1.35', 'Road Trips, Classic Cars & Motorbike Culture', 4),
  ('1.36', 'Kitchen Hacks That Save Time, Money & Effort Every Day', 0),
  ('1.36', 'Cleaning Hacks for Every Room — Spotless Home in Minutes', 1),
  ('1.36', 'Money-Saving Hacks — Spend Less Without Sacrificing Quality', 2),
  ('1.36', 'DIY Fixes & Creative Problem Solving at Home', 3),
  ('1.36', 'Phone & Tech Hacks That Save Hours Every Week', 4),
  ('1.37', 'Song Meanings & Lyrics Decoded — Songs You Misunderstood', 0),
  ('1.37', 'Best Music of Every Genre — Pop, Rock, Hip-Hop, Classical, Indian', 1),
  ('1.37', 'AI Music Creation with Suno — How to Make Songs from Scratch', 2),
  ('1.37', 'Music Legends — A.R. Rahman, SP Balu, Ilaiyaraaja & Global Greats', 3),
  ('1.37', 'Best Movie Songs & Background Scores — Cinematic Music Magic', 4),
  ('1.38', 'Latest Uploads', 0),
  ('1.39', 'Latest Uploads', 0)
ON CONFLICT (channel_sno, playlist_name) DO NOTHING;

-- Social accounts (36)
DELETE FROM social_links;
INSERT INTO social_links (platform, handle, url, icon_key, brand_color, group_name, display_order, is_active) VALUES
  ('YouTube (official)', '@PujithSakhamuri', 'https://www.youtube.com/@PujithSakhamuri', 'yt', '#ff0000', 'Video & audio', 0, true),
  ('LinkedIn (personal)', 'pujith-sakhamuri-06b69a137', 'https://www.linkedin.com/in/pujith-sakhamuri-06b69a137/', 'li', '#0a66c2', 'Professional', 1, true),
  ('LinkedIn (Pujiverse)', 'pujiverse-pujith', 'https://www.linkedin.com/in/pujiverse-pujith-700819392/', 'li', '#0a66c2', 'Professional', 2, true),
  ('GitHub', 'pujiverse', 'https://github.com/pujiverse', 'github', '#6e7681', 'Professional', 3, true),
  ('Product Hunt', '@pujiverse', 'https://www.producthunt.com/@pujiverse', 'producthunt', '#da552f', 'Professional', 4, true),
  ('Behance', 'pujiverse', 'https://www.behance.net/pujiverse', 'behance', '#1769ff', 'Design', 5, true),
  ('Dribbble', 'pujiverse', 'https://dribbble.com/pujiverse', 'dribbble', '#ea4c89', 'Design', 6, true),
  ('Sketchfab', 'Pujiverse', 'https://sketchfab.com/Pujiverse', 'sketchfab', '#1caad9', 'Design', 7, true),
  ('Instagram', '@pujiverseofficial', 'https://www.instagram.com/pujiverseofficial/', 'ig', '#e1306c', 'Social', 8, true),
  ('Facebook', 'pujiverseofficial', 'https://www.facebook.com/pujiverseofficial/', 'fb', '#1877f2', 'Social', 9, true),
  ('Threads', '@pujiverseofficial', 'https://www.threads.net/@pujiverseofficial', 'threads', '#4b5563', 'Social', 10, true),
  ('X (Twitter)', '@pujiverse', 'https://x.com/pujiverse', 'x', '#6b7280', 'Social', 11, true),
  ('Bluesky', 'pujiverse.bsky.social', 'https://bsky.app/profile/pujiverse.bsky.social', 'bluesky', '#0085ff', 'Social', 12, true),
  ('Pinterest', 'pujiverse', 'https://in.pinterest.com/pujiverse/', 'pi', '#e60023', 'Social', 13, true),
  ('Reddit', 'u/pujiverse', 'https://www.reddit.com/user/pujiverse/', 'reddit', '#ff4500', 'Social', 14, true),
  ('Telegram', '@pujiverse', 'https://t.me/pujiverse', 'telegram', '#26a5e4', 'Social', 15, true),
  ('WhatsApp', 'Pujith Sakhamuri', 'https://wa.me/message/HPIAGRGKO23SM1', 'wa', '#25d366', 'Social', 16, true),
  ('TikTok', '@pujiverse', 'https://www.tiktok.com/@pujiverse', 'tt', '#25b8c0', 'Video & audio', 17, true),
  ('Twitch', 'pujiverse_ai', 'https://www.twitch.tv/pujiverse_ai', 'twitch', '#9146ff', 'Video & audio', 18, true),
  ('Rumble', 'pujiverse', 'https://rumble.com/user/pujiverse', 'rumble', '#85c742', 'Video & audio', 19, true),
  ('Vimeo', 'pujiverse', 'https://vimeo.com/pujiverse', 'vimeo', '#1ab7ea', 'Video & audio', 20, true),
  ('Dailymotion', 'PUJIVERSE', 'https://www.dailymotion.com/PUJIVERSE', 'dm', '#00aaff', 'Video & audio', 21, true),
  ('SoundCloud', 'pujiverse', 'https://soundcloud.com/pujiverse', 'soundcloud', '#ff5500', 'Video & audio', 22, true),
  ('Snapchat Spotlight', 'pujiverse official', 'https://snapchat.com/t/bprrYRF8', 'snapchat', '#e6b800', 'Video & audio', 23, true),
  ('Likee', 'pujiverse', 'https://l.likee.video/p/h1YdV', 'likee', '#ff3c7e', 'Video & audio', 24, true),
  ('Kwai', '@Pujiverse', 'https://k.kwai.com/u/@Pujiverse/2sGeerCN', 'kwai', '#ff7a00', 'Video & audio', 25, true),
  ('Moj', '@pujiverse', 'https://mojapp.in/@pujiverse', 'moj', '#f9a825', 'Video & audio', 26, true),
  ('Trendo', 'pujiverse', 'https://s.trendo.vip/Jjoq', 'trendo', '#8b5cf6', 'Video & audio', 27, true),
  ('IMDb', 'Pujiverse', 'https://www.imdb.com/user/p.aclcmdbqqkrtmxcppzezlcxolq/', 'imdb', '#d4a90c', 'Video & audio', 28, true),
  ('Substack', '@pujiverse', 'https://substack.com/@pujiverse', 'ss', '#ff6719', 'Writing', 29, true),
  ('Medium', '@pujiverse', 'https://medium.com/@pujiverse', 'me', '#02b875', 'Writing', 30, true),
  ('Blogger', 'pujiverse.blogspot.com', 'https://pujiverse.blogspot.com/', 'blogger', '#ff5722', 'Writing', 31, true),
  ('Tumblr', 'pujiverse', 'https://www.tumblr.com/pujiverse', 'tumblr', '#36465d', 'Writing', 32, true),
  ('Quora', 'Pujiverse', 'https://www.quora.com/profile/Pujiverse', 'qu', '#b92b27', 'Writing', 33, true),
  ('Patreon', 'pujithchowdarysakhamuri', 'https://www.patreon.com/cw/pujithchowdarysakhamuri', 'patreon', '#ff424d', 'Support & shop', 34, true),
  ('Etsy', 'pujiverse', 'https://www.etsy.com/people/jqo8bz5apmta83y3', 'etsy', '#f1641e', 'Support & shop', 35, true);

-- Websites (29 live + 3 in progress)
DELETE FROM websites;
INSERT INTO websites (id, title, url, description, category, tech, host, repo, tags, accent, is_live, display_order) VALUES
  ('pujiverse-home', 'Pujiverse Home (Network Hub)', 'https://pujiverse.github.io/Pujiverse-Network/', 'Main home page for the Pujiverse Network: channels, projects and apps in one place', 'Home', 'HTML/JS', 'GitHub Pages', 'https://github.com/pujiverse/Pujiverse-Network', ARRAY['Home', 'GitHub Pages']::text[], '#f59e0b', true, 0),
  ('ai-timeline', 'The AI Timeline', 'https://pujiverse.github.io/The-AI-Timeline/', 'Interactive history of AI from 1843 to today: era timeline, release tracker, model library and comparisons', 'Featured data platform', 'HTML/JS', 'GitHub Pages', 'https://github.com/pujiverse/The-AI-Timeline', ARRAY['Featured data platform', 'GitHub Pages']::text[], '#22d3ee', true, 1),
  ('vehicle-universe', 'Vehicle Universe', 'https://pujiverse.github.io/Vehicle-Universe/', 'Every vehicle from bicycles to rockets: 57 types, 3,400+ brands, 59,000+ models', 'Featured data platform', 'HTML/JS, BigQuery', 'GitHub Pages', 'https://github.com/pujiverse/Vehicle-Universe', ARRAY['Featured data platform', 'GitHub Pages']::text[], '#22d3ee', true, 2),
  ('world-atlas', 'Pujiverse World Atlas', 'https://pujiverse.github.io/pujiverse-world-atlas/', '3D globe population explorer, world to city, 2015–2025 trends and water bodies', 'Featured data platform', 'HTML/JS, BigQuery', 'GitHub Pages', 'https://github.com/pujiverse/pujiverse-world-atlas', ARRAY['Featured data platform', 'GitHub Pages']::text[], '#22d3ee', true, 3),
  ('bizmanager-lite', 'BizManager Lite', 'https://pujiverse.github.io/ledger/', 'Dependency-free business, chit, loan and household expense manager', 'Web app & tool', 'HTML/CSS/JS', 'GitHub Pages', 'https://github.com/pujiverse/ledger', ARRAY['Web app & tool', 'GitHub Pages']::text[], '#4ade80', true, 4),
  ('household-firebase', 'Household Expense Manager (Firebase)', 'https://pujiverse.github.io/HouseholdExpenseManager/', 'Multi-page expense, business and chit manager with Firebase Authentication', 'Web app & tool', 'JavaScript, Firebase', 'GitHub Pages', 'https://github.com/pujiverse/HouseholdExpenseManager', ARRAY['Web app & tool', 'GitHub Pages']::text[], '#4ade80', true, 5),
  ('expense-sheets', 'Expense Manager (Google Sheets)', 'https://pujiverse.github.io/Expense-Manager/', 'Household expense, business, chit and loan tracker backed by Google Sheets', 'Web app & tool', 'JavaScript, Google Sheets API', 'GitHub Pages', 'https://github.com/pujiverse/Expense-Manager', ARRAY['Web app & tool', 'GitHub Pages']::text[], '#4ade80', true, 6),
  ('auto-portfolio', 'Auto-Updating Portfolio', 'https://pujiverse.github.io/pujith-portfolio/', 'Portfolio that pulls its content live from a Google Sheet', 'Web app & tool', 'JavaScript, Google Sheets', 'GitHub Pages', 'https://github.com/pujiverse/pujith-portfolio', ARRAY['Web app & tool', 'GitHub Pages']::text[], '#4ade80', true, 7),
  ('network-master-data', 'Pujiverse Network Master Data', 'https://pujiverse.github.io/PujiverseNetwork/', 'Master data for the channels in the Pujiverse Network', 'Web app & tool', 'HTML/JS', 'GitHub Pages', 'https://github.com/pujiverse/PujiverseNetwork', ARRAY['Web app & tool', 'GitHub Pages']::text[], '#4ade80', true, 8),
  ('voice-studio', 'Pujiverse Voice Studio', 'https://pujiverse-voice-studio.vercel.app/', 'Text-to-speech voice-overs with selectable age, gender and emotion', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/Pujiverse-Voice-Studio', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 9),
  ('video-creator', 'YouTube Video Creator', 'https://puji-verse-video-content-creator.vercel.app/', 'Scripts, voice-overs and background music for YouTube videos', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/PujiVerse-Video-Content-Creator', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 10),
  ('creation-spark', 'Pujiverse Creation Spark', 'https://pujiverse-creative-spark.vercel.app/', 'Turns an idea into songs, stories or narrations in multiple languages', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/Creative-Spark', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 11),
  ('recipe-voiceover', 'Recipe Voice-over Generator', 'https://pujiverse-recipe-voice-over-generat.vercel.app/', 'Multilingual cooking voice-overs from recipe steps', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/Recipe-Voice-over-Generator', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 12),
  ('cinema-storyteller', 'Pujiverse Cinema Storyteller', 'https://pujiverse-cinema.vercel.app/', 'Movie scripts and voice-overs in Telugu–English', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/pujiverse-cinema', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 13),
  ('subtitle-to-story', 'Movie Storyteller & Live AI', 'https://pujiverse-subtitle-to-story.vercel.app/', 'Stories from subtitles, transcript analysis and live voice chat', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/movie-subtitle-to-story', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 14),
  ('text-to-audio', 'Text to Audio', 'https://voice-three-blush.vercel.app/', 'Simple text-to-audio generator', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/voice', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 15),
  ('vidprompt-studio', 'VidPrompt Studio', 'https://pujiverse-vid-prompt-studio-new.vercel.app/', 'Prompt-driven video trimming, narration and in-browser editing', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/VidPrompt-Studio_new', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 16),
  ('smart-scene-cutter', 'SmartSceneCutter', 'https://smart-scene-cutter.vercel.app/', 'Cuts and merges clips from prompts and timestamps; generates FFmpeg commands', 'Google AI Studio app', 'TypeScript, React, Gemini API, FFmpeg.wasm', 'Vercel', 'https://github.com/pujiverse/SmartSceneCutter', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 17),
  ('text-to-video', 'Text-to-Video Generator', 'https://pujiverse-text-to-video.vercel.app/', 'Prompt-to-video with aspect-ratio and resolution control', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/text-to-video', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 18),
  ('presentation-generator', 'Presentation Generator', 'https://ai-animated-presentation-generator.vercel.app/', 'Animated PPTX slides with voice-over from a single topic', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/AI-Animated-Presentation-Generator', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 19),
  ('ppt-voiceover', 'PPT Voiceover Generator', 'https://pujiverse-ppt-voiceover-generator.vercel.app/', 'Per-slide voice-overs with playback and download', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/PPT-Voiceover-Generator', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 20),
  ('resume-builder', 'Pujiverse Resume Builder', 'https://resume-builder-azure-omega.vercel.app/', 'Tailors a resume to a job description', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/resume-builder', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 21),
  ('sai-indian', 'Sai Indian Cuisine Digital Concierge', 'https://sai-indian.vercel.app/', 'Mobile-first restaurant landing page with an AI concierge', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/SAI-INDIAN', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 22),
  ('business-manager-pro', 'Business Manager Pro', 'https://biz-manager-eight.vercel.app/', 'Business, chit, expense and loan tracking with reports', 'Google AI Studio app', 'TypeScript, React, Supabase, Recharts', 'Vercel', 'https://github.com/pujiverse/biz-manager', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 23),
  ('pujiverse-hub-v1', 'Pujiverse Hub (earlier version)', 'https://pujiverse.vercel.app/', 'First version of the personal hub for socials, projects and contact', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/pujiverse-hub', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 24),
  ('live-sync-portfolio', 'Live-Sync Portfolio', 'https://pujithsakhamuri.vercel.app/', 'Google-Sheet-synced portfolio with a Gemini assistant', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/New-Portfolio', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 25),
  ('professional-portfolio', 'Professional Portfolio', 'https://pujith-sakhamuri-portfolio.vercel.app/', 'Career portfolio', 'Google AI Studio app', 'TypeScript, React, Gemini API', 'Vercel', 'https://github.com/pujiverse/my-protfolio', ARRAY['Google AI Studio app', 'Vercel']::text[], '#c084fc', true, 26),
  ('aiml-500-portfolio', 'AIML-500 Professional Portfolio', 'https://pujiverse.github.io/pujith_portfolio/', 'Professional portfolio for AIML-500 (Indiana Wesleyan University)', 'Academic', 'HTML', 'GitHub Pages', 'https://github.com/pujiverse/pujith_portfolio', ARRAY['Academic', 'GitHub Pages']::text[], '#f472b6', true, 27),
  ('github-profile', 'GitHub Profile README', 'https://github.com/pujiverse', 'Profile page with projects, channels and links', 'Profile', 'Markdown', 'GitHub', 'https://github.com/pujiverse/pujiverse', ARRAY['Profile', 'GitHub']::text[], '#94a3b8', true, 28),
  ('film-database', 'Pujiverse Film Database', 'https://github.com/pujiverse/Pujiverse-Film-Database', 'IMDb-style database of movies, short films, anime and TV across world film industries', 'Featured data platform', 'HTML/JS', 'GitHub Pages', 'https://github.com/pujiverse/Pujiverse-Film-Database', ARRAY['Featured data platform', 'GitHub Pages']::text[], '#22d3ee', false, 29),
  ('flypal', 'FlyPal', 'https://github.com/pujiverse/FlyPal', 'Concept: real-time social matching app for airport layovers', 'Web app & tool', '—', '—', 'https://github.com/pujiverse/FlyPal', ARRAY['Web app & tool', '—']::text[], '#4ade80', false, 30),
  ('vidprompt-v1', 'VidPrompt Studio (earlier version)', 'https://github.com/pujiverse/VidPrompt-Studio', 'Earlier offline-first version of VidPrompt Studio', 'Google AI Studio app', 'TypeScript, React, Gemini API', '—', 'https://github.com/pujiverse/VidPrompt-Studio', ARRAY['Google AI Studio app', '—']::text[], '#c084fc', false, 31);

-- Home page planets + contact email (edit later in Admin -> Home Page)
INSERT INTO site_settings (key, value) VALUES ('home', '{"email":"pujiverse@gmail.com","planets":{"youtube":{"label":"YouTube","sub":"","emo":"▶","color":"#ef4444","show":true},"about":{"label":"About Me","sub":"Profile · experience · skills","emo":"🧑‍🚀","color":"#f59e0b","href":"","show":true},"info":{"label":"Personal Info","sub":"Portfolio","emo":"🪪","color":"#22d3ee","href":"https://pujith-sakhamuri-portfolio.vercel.app/","show":true},"social":{"label":"Social Hub","sub":"","emo":"🌐","color":"#c084fc","show":true},"websites":{"label":"Websites","sub":"","emo":"💻","color":"#4ade80","show":true}}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Profile (About Me) so BigQuery and future pages can use it
INSERT INTO site_settings (key, value) VALUES ('profile', '{"name":"Pujith Chowdary Sakhamuri","short":"Pujith Sakhamuri","headline":"Full Stack Data & AI Engineer | GCP · BigQuery · Dataflow · Vertex AI · Gemini API | Network Data Analyst @ Telka (T-Mobile) | Pujiverse Creator","tagline":"Full Stack Data & AI Engineer · Network Data Analyst · Pujiverse Creator","location":"Celina, Texas, United States","email":"pujiverse@gmail.com","officialChannel":{"name":"Pujith Sakhamuri","handle":"@PujithSakhamuri","url":"https://www.youtube.com/@PujithSakhamuri"},"links":{"home":"https://pujiverse.github.io/Pujiverse-Network/","portfolio":"https://pujith-sakhamuri-portfolio.vercel.app/","github":"https://github.com/pujiverse","resume":"https://github.com/pujiverse/pujiverse/blob/main/resume.pdf","linkedin":"https://www.linkedin.com/in/pujith-sakhamuri-06b69a137/"},"about":"I build data platforms and AI tools, from pipelines and semantic models on Google Cloud to web apps people use. Network Data Analyst at Telka supporting T-Mobile; previously Full Stack Data & AI Engineer for CVS Pharmacy (SR Systems) and Data Engineer for Cleveland Clinic (IvyNova). Creator of Pujiverse: 39 YouTube channels plus interactive projects like The AI Timeline, Vehicle Universe and the Pujiverse World Atlas.","stats":{"projects":32,"live":29,"githubPages":11,"vercel":18,"aiStudio":19,"channels":39,"platforms":37,"experience":8},"experience":[{"company":"Pujiverse Network","title":"Creator & Founder","type":"Self-employed","location":"Remote","start":"Mar 2025","end":"Present","text":"Built and run a network of 39 YouTube channels, interactive data projects (The AI Timeline, Vehicle Universe, World Atlas) and 18+ Gemini-powered apps.","link":"https://pujiverse.github.io/Pujiverse-Network/"},{"company":"Telka LLC","title":"Network Data Analyst","type":"Full-time","location":"Prosper, TX (client: T-Mobile, Central Region)","start":"Aug 2026","end":"Present","text":"5G/LTE drive-test data and RF metrics (RSRP, RSRQ, SINR, throughput); Python/SQL log validation; FCC compliance audits; weekly KPI dashboards."},{"company":"Alignerr","title":"AI & LLM Evaluation Specialist","type":"Contract","location":"Remote","start":"Jan 2025","end":"Present","text":"Evaluate LLM outputs on Python, SQL and multi-step reasoning under RLHF guidelines; build tool-calling validation datasets."},{"company":"Upwork","title":"Full Stack & Generative AI Developer","type":"Freelance","location":"Remote","start":"Jan 2024","end":"Present","text":"Web apps and AI tools for small businesses with React, TypeScript, Python and the Gemini API on Vercel and Cloud Run."},{"company":"SR Systems LLC","title":"Full Stack Data & AI Engineer","type":"Full-time","location":"Texas (client: CVS Pharmacy)","start":"Jul 2024","end":"Jul 2026","text":"BigQuery semantic models for Vertex AI; Dataflow, Pub/Sub, Cloud Composer pipelines; Cloud Run APIs; Terraform and GitHub Actions; HIPAA data governance."},{"company":"Ivynova Solutions, Inc.","title":"Data Engineer","type":"Full-time","location":"Cleveland, OH (client: Cleveland Clinic)","start":"Jun 2023","end":"Jul 2024","text":"GCS ingestion of clinical feeds; Cloud Functions and Airflow DAGs (99.8% data accuracy); star-schema models in BigQuery for BI."},{"company":"Cleveland State University","title":"Graduate Assistant, Data Analytics & Infrastructure Support","type":"Part-time","location":"Cleveland, OH","start":"Mar 2022","end":"May 2023","text":"SQL reporting datasets, automated ETL workflows, Power BI and Tableau dashboards, data validation checks."},{"company":"Self-employed","title":"Freelance Developer / Data Analyst","type":"Freelance","location":"Hyderabad, India","start":"Oct 2020","end":"Jan 2022","text":"Mentored engineering students on academic projects; built web applications; debugging and project documentation."}],"education":[{"school":"Indiana Wesleyan University","degree":"Master of Science","field":"Artificial Intelligence & Machine Learning","start":"Jul 2026","end":"Dec 2027 (expected)","notes":"Coursework: AIML-500 Machine Learning Fundamentals, DTAN-500 Foundations of Data Analytics, DTAN-505 Data Visualization (R)"},{"school":"Cleveland State University","degree":"Master of Science","field":"Computer and Information Sciences","start":"Jan 2022","end":"May 2023","notes":"Graduate Assistant, Data Analytics & Infrastructure Support"},{"school":"JNTUH","degree":"Bachelor of Technology","field":"Computer Science and Engineering","start":"2016","end":"2020","notes":""}],"skills":[{"area":"Cloud & Data Platform","items":"Google Cloud Platform (GCP), Google BigQuery, Vertex AI, Cloud Dataflow, Pub/Sub, Cloud Composer, Apache Airflow, Cloud Run, Cloud Functions, Cloud Storage"},{"area":"AI & Machine Learning","items":"Generative AI, Gemini API, Large Language Models, AI Agents, Google ADK, Prompt Engineering, Machine Learning, RLHF evaluation"},{"area":"Data Engineering & Analytics","items":"Data Engineering, Data Modeling, Dimensional Modeling, Semantic Modeling, ETL, Data Pipelines, Data Governance, Data Quality, HIPAA Compliance, KPI Analysis, RF Analytics (5G/LTE)"},{"area":"Programming","items":"Python, SQL, PySpark, R, TypeScript, JavaScript, HTML, CSS"},{"area":"Web & App Development","items":"React, FastAPI, REST APIs, Firebase, Supabase, PostgreSQL, MySQL, Vercel, GitHub Pages"},{"area":"DevOps","items":"Terraform, Docker, GitHub Actions, CI/CD, Git, Linux"},{"area":"BI & Visualization","items":"Power BI, Tableau, Data Visualization, Dashboard Design"},{"area":"Creative","items":"Content Creation, Video Production, YouTube, Brand Identity, Web Design, UI/UX Design"}]}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

COMMIT;
